/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EventInput = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Int,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'price' : IDL.Nat,
  'location' : IDL.Text,
});
export const ReservationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const ReservationOutput = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReservationStatus,
  'eventId' : IDL.Nat,
  'transactionNote' : IDL.Text,
  'eventDetails' : Event,
  'submittedAt' : Time,
  'imvuUsername' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'imvuUsername' : IDL.Text,
});
export const ReservationUpdate = IDL.Record({
  'id' : IDL.Nat,
  'status' : ReservationStatus,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addEvent' : IDL.Func([EventInput], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [], []),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllReservations' : IDL.Func([], [IDL.Vec(ReservationOutput)], ['query']),
  'getAllReservationsForEvent' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ReservationOutput)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [ReservationOutput], ['query']),
  'getReservationsByUsername' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ReservationOutput)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitReservation' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateReservation' : IDL.Func([ReservationUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EventInput = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Int,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'price' : IDL.Nat,
    'location' : IDL.Text,
  });
  const ReservationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReservationOutput = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReservationStatus,
    'eventId' : IDL.Nat,
    'transactionNote' : IDL.Text,
    'eventDetails' : Event,
    'submittedAt' : Time,
    'imvuUsername' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'imvuUsername' : IDL.Text,
  });
  const ReservationUpdate = IDL.Record({
    'id' : IDL.Nat,
    'status' : ReservationStatus,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addEvent' : IDL.Func([EventInput], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [], []),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllReservations' : IDL.Func(
        [],
        [IDL.Vec(ReservationOutput)],
        ['query'],
      ),
    'getAllReservationsForEvent' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ReservationOutput)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReservation' : IDL.Func([IDL.Nat], [ReservationOutput], ['query']),
    'getReservationsByUsername' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ReservationOutput)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitReservation' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateReservation' : IDL.Func([ReservationUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };